"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.API_DELETE_METHOD = exports.API_PUT_METHOD = exports.API_GET_METHOD = exports.API_POST_METHOD = exports.API_FORM_CONTENT_TYPE = exports.API_JSON_CONTENT_TYPE = exports.API_SECURITY_TYPE_JWT = exports.API_SECURITY_TYPE_BEARER = exports.API_DEFAULT_CACHE = exports.API_DEFAULT_AUTH_TYPE = exports.API_DEFAULT_SECURE = exports.API_DEFAULT_METHOD = exports.API_DEFAULT_ENDPOINT = exports.API_DEFAULT_SERVER_URL = exports.API_DEFAULT_TIMEOUT = void 0;
// General API Configuration
var API_DEFAULT_TIMEOUT = 20000;
exports.API_DEFAULT_TIMEOUT = API_DEFAULT_TIMEOUT;
var API_DEFAULT_SERVER_URL = 'http://localhost:8080';
exports.API_DEFAULT_SERVER_URL = API_DEFAULT_SERVER_URL;
var API_DEFAULT_ENDPOINT = '/';
exports.API_DEFAULT_ENDPOINT = API_DEFAULT_ENDPOINT;
var API_DEFAULT_METHOD = 'GET';
exports.API_DEFAULT_METHOD = API_DEFAULT_METHOD;
var API_DEFAULT_SECURE = false;
exports.API_DEFAULT_SECURE = API_DEFAULT_SECURE;
var API_DEFAULT_AUTH_TYPE = 'JWT';
exports.API_DEFAULT_AUTH_TYPE = API_DEFAULT_AUTH_TYPE;
var API_DEFAULT_CACHE = 'no-cache';
exports.API_DEFAULT_CACHE = API_DEFAULT_CACHE;
var API_SECURITY_TYPE_BEARER = 'Bearer';
exports.API_SECURITY_TYPE_BEARER = API_SECURITY_TYPE_BEARER;
var API_SECURITY_TYPE_JWT = 'JWT';
exports.API_SECURITY_TYPE_JWT = API_SECURITY_TYPE_JWT;
var API_JSON_CONTENT_TYPE = 'application/json';
exports.API_JSON_CONTENT_TYPE = API_JSON_CONTENT_TYPE;
var API_FORM_CONTENT_TYPE = 'application/x-www-form-urlencoded';
exports.API_FORM_CONTENT_TYPE = API_FORM_CONTENT_TYPE;
var API_POST_METHOD = 'POST';
exports.API_POST_METHOD = API_POST_METHOD;
var API_GET_METHOD = 'GET';
exports.API_GET_METHOD = API_GET_METHOD;
var API_PUT_METHOD = 'PUT';
exports.API_PUT_METHOD = API_PUT_METHOD;
var API_DELETE_METHOD = 'DELETE';
exports.API_DELETE_METHOD = API_DELETE_METHOD;