const logout = require('./logout')
const login = require('./login')
const register = require('./register')
const say = require('./say')
const create = require('./create')
const list = require('./list')
const next = require('./next')
const publish = require('./publish')
const start = require('./start')
const pause = require('./pause')
const lock = require('./lock')
const unlock = require('./unlock')
const config = require('./config')

module.exports = { login, config, lock, unlock, start, pause, logout, register, say, create, list, next, publish }
